#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2018 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++


###################################
#
# This file was generated by
# openproject-devkit.
#
# Do not modify this file directly!
#
###################################

language: ruby

rvm:
  - 2.5.1

sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - frontend/node_modules

branches:
  only:
    - master
    - dev
    - /^(stable|release)\/.*$/

env:
  global:
    - CI=true
    - RAILS_ENV=test

  matrix:
    - "TEST_SUITE=plugins:specs     DB=mysql    GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=plugins:features  DB=mysql    GROUP_SIZE=1 GROUP=1"



before_install:
  ## Custom plugin instructions follow.
  # Move the plugin into a subfolder. The plugin-provided Gemfile.plugins
  # must refer to this folder.
  - mkdir -p plugins/this
  - echo `ls -a | tail -n+3 | grep -v plugins` plugins/this/ | xargs mv

  # Get OpenProject.
  # Doing the fetch detour as you cannot clone into the current directory.
  - git init
  - git remote add openproject https://github.com/opf/openproject.git
  - git fetch --depth=1 openproject
  - git checkout openproject/$TRAVIS_BRANCH

  # Install pandoc for testing textile migration
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq pandoc

  # Install Node latest LTS
  - "nvm install --lts"
  # work around https://github.com/travis-ci/travis-ci/issues/8969
  - travis_retry gem update --system
  # Don't install 1.16.3
  - gem install bundler -v 1.16.2


bundler_args: --binstubs --without development production docker

before_script:
  - bash script/ci_setup.sh $TEST_SUITE $DB

script:
  - bash script/ci_runner.sh


addons:
  chrome: stable
  postgresql: "9.6"
